import { Geist, Geist_Mono, Noto_Sans_JP } from "next/font/google";
import "./globals.css";
import Providers from "./provider";
import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistNoto = Noto_Sans_JP({
  variable: "--font-noto-sans-jp",
  subsets: ["latin"],
});

export const metadata = {
  title: "Unboarding",
  description: "Generated by humans",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`font-sans ${geistNoto.variable} antialiased`}>
        <Providers>{children}</Providers>
        <Toaster position="top-right" duration={100000} />
      </body>
    </html>
  );
}
